from src.preprocessing import RetailPreprocessor
preprocessor = RetailPreprocessor()
preprocessor.load_data("data/raw/one year ebo sale data.xlsx")
preprocessor.detect_columns()
preprocessor.rename_columns()
df=preprocessor.remove_empty_columns()
df=preprocessor.standardize_text_columns()
print("before convert_data_types", df.dtypes)
df=preprocessor.convert_data_types()
print(df.columns.tolist())
print("After convert_data_types:", df.dtypes)