project_name: Retail Demand Forecasting
target_column: qty
aggregation_level:
  - date
  - store
  - style
  - color
  - size
aggregation_rules:

  qty: sum

  amount: sum

  rate: mean

  category: first

  description: first

  state: first

  channel: first
train_ratio: 0.8
random_state: 42
model:
  algorithm: catboost
  save_model: true
processed_data_path: data/processed/
prediction_path: data/predictions/