date:
  datatype: datetime
qty:
  datatype: integer
  minimum: 0
rate:
  datatype: float
  minimum: 0.0
amount:
  datatype: float
  minimum: 0.0
required_columns:
  - date
  - store
  - style
  - color
  - size
  - qty
  - rate
  - amount