date:
  datatype: datetime
  required: true

style:
  datatype: string
  required: true

store:
  datatype: string
  required: true

color:
  datatype: string
  required: true

size:
  datatype: string
  required: true

qty:
  datatype: integer
  required: true
  min: 0

rate:
  datatype: float
  required: false
  min: 0

amount:
  datatype: float
  required: false

channel:
  datatype: string
  required: false
  allowed_values:
    - EBO
    - MBO
    - ECOM

state:
  datatype: string
  required: false